### ISSUE TITLE
all_trace results view of db + cohort filter

### ISSUE THREAD

**Issue by tkv29** [bptlab/TracEX#105]
- [x] view where all_traces is displayed and has all filter options (event type, location and incoming activity key #85 ) like results page
- [x]  has button for landing page
- [x] add cohort filter as a selectable scrollable window so that it fits the design but also is able to handle many cohorts as multiple choice

![Image](https://github.com/bptlab/TracEX/assets/73845255/f58e499f-b624-4769-b4fd-9bee586a41ab)

**Comment by nils-schmitt** [comment]
And you should use the condition in the metrics analyzer
