### ISSUE TITLE
Code check: tracex + PJ generator

### ISSUE THREAD

**Issue by tkv29** [bptlab/TracEX#133]
This task includes checking for readability (magic numbers, outsource too long code in functions, meaningful docstrings etc.).

**Comment by tkv29** [comment]
<img width="626" alt="image" src="https://github.com/bptlab/TracEX/assets/73845255/ad225398-90cd-4ec6-952d-27ffd113c6a2">

**Comment by tkv29** [comment]
<img width="684" alt="image" src="https://github.com/bptlab/TracEX/assets/73845255/2d9dc396-1977-41fe-b9e6-063e4bd40dbd">

**Comment by tkv29** [comment]
![image](https://github.com/bptlab/TracEX/assets/73845255/d68e2e83-6523-45b9-8208-7d2e56e115a1)
<img width="342" alt="image" src="https://github.com/bptlab/TracEX/assets/73845255/92fae9df-1d3f-4248-a625-22e311c4e0d8">

**Comment by tkv29** [comment]
<img width="663" alt="image" src="https://github.com/bptlab/TracEX/assets/73845255/1cb01831-bb8c-4729-afc7-b127b2e943cf">

**Comment by tkv29** [comment]
<img width="594" alt="image" src="https://github.com/bptlab/TracEX/assets/73845255/72f44bf9-65b1-48fc-b29b-90728d6306b0">
fix sizing

**Comment by PitButtchereit** [comment]
> <img alt="image" width="684" src="https://private-user-images.githubusercontent.com/73845255/331537508-2d9dc396-1977-41fe-b9e6-063e4bd40dbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODY0MDAsIm5iZiI6MTcxNjI4NjEwMCwicGF0aCI6Ii83Mzg0NTI1NS8zMzE1Mzc1MDgtMmQ5ZGMzOTYtMTk3Ny00MWZlLWI5ZTYtMDYzZTRiZDQwZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEwMDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYWEyNmJjNDA4Y2M2NTQ5MjU1ZmNhOTMyNjFiY2EwNTVhMTBlZTU3ZWMxMGQ4NDk4ZDQyY2Y2NWQ0ZmUwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kSs83BO0nztisCWSt79zZUheG9Ebhl6OFRbOujWKX70">

Should be universal for the entire application?

**Comment by PitButtchereit** [comment]
> width is weird <img alt="image" width="594" src="https://private-user-images.githubusercontent.com/73845255/331551319-72f44bf9-65b1-48fc-b29b-90728d6306b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODY0MDAsIm5iZiI6MTcxNjI4NjEwMCwicGF0aCI6Ii83Mzg0NTI1NS8zMzE1NTEzMTktNzJmNDRiZjktNjViMS00OGZjLWIyOWItOTA3MjhkNjMwNmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEwMDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzOGFhNWQzYmVjZTUyNzUxMzdjY2RhMzdmN2ZjODAzYTEwYWU0Mjg3ZWQyYWQ1Y2FiM2QwNzAwYjk2YjM2OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NzV4nA3Tr3aIsKrGwGWEONak0j7Ih2GziU3157UupBs"> fix sizing

I've adjusted the size:


![Image](https://github.com/bptlab/TracEX/assets/116184086/38f76d25-d92f-4ac2-a7a2-04689309eaec)

**Comment by PitButtchereit** [comment]
> should be done after the PR for normalizing is being merged on main <img alt="image" width="663" src="https://private-user-images.githubusercontent.com/73845255/331538036-1cb01831-bb8c-4729-afc7-b127b2e943cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDkzNzYsIm5iZiI6MTcxNjU0OTA3NiwicGF0aCI6Ii83Mzg0NTI1NS8zMzE1MzgwMzYtMWNiMDE4MzEtYmI4Yy00NzI5LWFmYzctYjEyN2IyZTk0M2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDExMTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YTY0MWQ4OTkwNWYyMDlkZjQxNWI4ZjU5NTUxODkyY2JiYjA1NmRiNDRkNjVkNmZlYTc4NDQ5ZGM4NDRkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PYmWQ2O9PBfM1tCVFuDs9D-4GBgoCp5RzHwizBG-viI">

Final database adjustments will be made in #139

**Comment by PitButtchereit** [comment]
This code check is now ready to review 👍
