### ISSUE TITLE
Corporate Identity

### ISSUE THREAD

**Issue by PitButtchereit** [bptlab/TracEX#14]
As a team member, I want to represent my corporate identity, so that our team is recognizable and unified.

**Description:** The final product should be a slide master in english, with light design. Optionally a logo can be created.
Furthermore we will have a look into creating our own t-shirts.

**Estimated Size:** 1 week

# Definition of Ready
- [x] the user story still has room for discussion
- [ ] the user story must have value for the stakeholders
- [x] the user story has been drafted by at least 3 people

# Acceptance Criteria
- [x] a slide master is created and shared with the entire team
- [x] potx file

# Definition of Done
- [x] all acceptance criteria are fulfilled
- [x] presented to the team briefly

**Comment by FR-SON** [comment]
The optional goal of creating a logo was also achieved
