### ISSUE TITLE
First Process Mining Implementation

### ISSUE THREAD

**Issue by PitButtchereit** [bptlab/TracEX#25]
As a Stakeholder, I want to get a visualized view on the capabilities of the prototype, so that I can get an overview of the depth of the process-mining.

**Description:** Create traces from multiple patient journeys with regard to a set level (High/Mid/Low, see #23 for more information) and dense them into a visual map.

**Estimated Size:** L

**Dependent Issues:**
* #23 

# Acceptance Criteria
- [x] Every Event is categorized according to our event type framework
- [x] Every XES-Output gets stored.
- [x] One dedicated XES-File gets extended by every new patient journey converted.
- [x] A visual map gets created from that XES-File containing at least 30 patient journeys.

**Comment by nils-schmitt** [comment]
The resulting visual map of 31 generated traces.

![Image](https://github.com/bptlab/TracEX/assets/116206992/068052ee-fa77-4989-afe1-fba689e2f94d)
