### ISSUE TITLE
UI for prototype presentation

### ISSUE THREAD

**Issue by PitButtchereit** [bptlab/TracEX#26]
As a researcher, I want to have a user interface to access the pipeline , so that the functionality is illustrated and easily conveyed.

**Description:** Basic django UI that accesses the current iteration of the code. It displays the configuration options that have been implemented so far. (For example it offers a selection of event types from which one can choose)

**Estimated Size:** L

**Dependent Issues:** 

# Acceptance Criteria
- [x] Views
> - [x] There is a view where one can upload patient journeys and start the pipeline.
> - [x] There is a view that displays the results of the processed data, including a DFG.
> - [ ] There is a view where one can download the eventlog as XES file.

- [x] Code Restructuring
> - [x] The project is structured in a way so that the current functionality can easily be called upon.
> - [x] The code is refactored in a way so that you can directly map functions to its corresponing interactable element.

- [ ] MockUp
> - [ ] Shows the Layout/Design of each view.
> - [ ] Every needed view is represented.
> - [ ] Every interactable element is displayed and its functionality is obvious from its context or label.

**Comment by thangixd** [comment]
toDo week 5.12 xes downloading, styling the ui

@PitButtchereit we want to talk about the necessarity of the mockup on tuesday.

**Comment by PitButtchereit** [comment]
No mockup was needed. UI was finished until the prototype presentation.
