### ISSUE TITLE
Dataframes for consistent Bullet Point formatting

### ISSUE THREAD

**Issue by thangixd** [bptlab/TracEX#32]
As a developer, I want to improve the data handling by ensuring a consistent output using function calling and using pandas dataframes for storing GPT-generated respsones to enable seamless data extraction and improving internal processing efficiency.
 
**Description:**
Currently we are using bulletpoints as txts to pass internal information between different processing steps. This should be changed to pandas data frames. Artifacts can be derived from this by converting the data frame to for example csv. Currently we can't ensure a consistent response output based on the variability of the GPT model.

**Estimated Size:**
L

**Dependent Issues:** 

# Acceptance Criteria
- [x] internal processing only uses data frames
- [x] implementing function calling
- [x] adapt funtions for using dataframes
- [x] adapt pipeline steps for using function calling
- [x] implement functions for function calling

**Comment by soeren227** [comment]
either the function calling approach should be documented in the acceptance criteria of this user story or there should be a seperate user story for it
