### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by PitButtchereit** [bptlab/TracEX#54]
As a developer I want to have unit tests so that my code is tested.

**Comment by FR-SON** [comment]
I think there might be errors that should actually be handled as errors. Maybe there could be a view that displays that error (with suggestions on how to fix it)?
That's only necessary if we find such an error, but let's keep it in mind.

**Comment by PitButtchereit** [comment]
Suggestions on how to fix the error occured will be really dificult i imagine because we would have to classify what kind of error occured. Also why suggest on how to fix the error when we could just fix it in the first place and then no error occurs any longer :)
