### ISSUE TITLE
choosing PJ from DB

### ISSUE THREAD

**Issue by FR-SON** [bptlab/TracEX#66]
As a user, I want to use patient journeys in the extraction pipeline, so that I don't have to upload them again. It should be integrated in the journey upload view, so the user has the possibility to choose one from the db or upload a new one.

# Acceptance Criteria
- [x] on the the jouney input view theres a splitted screen where the user can choose an existing one or upload one
- [x] the view allows starting the pipeline with one selected patient journey (after choosing a method and the other method gets disabled)
- [x] when collecting the traces in `ResultView` only the newest traces of each patient journey should be used

**Comment by PitButtchereit** [comment]
I would suggest filling the database with a wide variety of patient journeys, both real-world and synthetic, to choose from after implementing this change. This should be a basis that also gets pushed to github so everyone gets access to these patient journeys.
