### ISSUE TITLE
Process Mining Metrics

### ISSUE THREAD

**Issue by nils-schmitt** [bptlab/TracEX#75]
As a developer, I want to evaluate the pipeline by applying typical Process Mining Metrics, so that I can evaluate the quality of the pipeline and used prompts.

**Description:** By implementing Process Mining Anomalies (i.e. Missing Activity, Wrong Order and Unexpected Activity) as metrics for our pipeline, we can improve the quality of its evaluation. 
- Missing Activity means an activity that is found in the groundtruth is not fround by the pipeline. 
- Wrong Order means every occasion of an activity that is found by the pipeline after an other one where the other one corresponds to an activity of the ground truth that is retrieved before the first activity of the pipeline result.
- Unexpected Activity means any activity in the pipeline result that is not included in the ground truth.

**Estimated Size:** M

**Dependent Issues:** #70 

# Acceptance Criteria
- [x] Missing Activity is implemented
- [x] Wrong Order is implemented
- [x] Unexpected Activity is implemented
- [x] Prompts are improved
- [ ] The results are shown to the team

**Comment by tkv29** [comment]
@PitButtchereit @soeren227 pls code review
