### ISSUE TITLE
Loading Prompts from the DB

### ISSUE THREAD

**Issue by tkv29** [bptlab/TracEX#82]
**Description:**
This tasks includes the uploading current prompts into the db and replacing calls in the code into db calls. 

# Acceptance Criteria
- [x] currently used prompts are all in the database
- [x] prompts calling are being replaced in the code as db calls

**Comment by FR-SON** [comment]
Suggestion: Add a `category` field to the prompts model. This way a user might use "only fewshot" prompts or "only chain of thought" prompts. If we event want that.
