### ISSUE TITLE
Implement GPT Key Request

### ISSUE THREAD

**Issue by tkv29** [bptlab/TracEX#87]
**Description:**
This tasks inlcudes the implementation of a UI for pasting in the gpt key

# Acceptance Criteria
- [x] in the landing page should be in the right corner anicon (key) or sth. where you can click on it 
- [x] after a pop up appears where you can change your gpt key
- [x] when clicking on app the access should be blocked by the pop up to force the user to enter a key

**Comment by PitButtchereit** [comment]
Isn't this the same description as #78?

**Comment by tkv29** [comment]
yess it was a copy paste mistake
