### ISSUE TITLE
Refactoring Code #1

### ISSUE THREAD

**Issue by tkv29** [bptlab/TracEX#89]
- [x] The Patient Journey Generator displays a GenerationForm in his views. Currently this class does not add any more functionality is is therefore redundant. This class needs to be refactored by either safe deleting it or adding necessary functionality.
- [x] Refactor the usage of the `execute` and `execute_and_save` functions of the modules. The function signature shall be the same. Keyword arguments shall be used when calling the functions for better readability.
- [x] Refactor the `rate_activity_relevance` function inside the Metrics Analyzer so that it is static and does not have any side effects that lead to errors.
- [x] All import statements inside the project will be refactored. This includes using absolute imports first. Secondly, imports will should be clustered together if possible e.g. modules can be imported with a more light syntax.
- [x] Refactor the `query_gpt` function so that it does not use function calls anymore. Remove all unnecessary code.
- [x] Refactor the main business logic of all modules by making the respective functions more readable and removing unnecessary functions. It will also be discussed with the group if we move the main logic into the execute function to remove unnecessary function calls and code lines. This would become the norm for writing new modules. Updates will be posted regarding this.
- [x] Implement that the Cohort Tagger uses the `execute_and_save` function so that cohorts are saved in the database.

**Comment by FR-SON** [comment]
The `execute` function should be called with keyword arguments, so it is clear is the given parameter is a text or a list of sentences. Especially since we will probably only ever use one of the two in any given call. The `*` enforces that. Furthermore the signature for `execute` and `execute_and_save` should be identical, aside from the return type. 
```
def execute(
        self, _input, *, patient_journey=None, patient_journey_sentences=None
    ) -> pd.DataFrame:
```

**Comment by FR-SON** [comment]
With #76 modules can be imported with `from extraction.logic.modules import [modulesname]`. We should change the imports wherever they are used, e.g. in `Orchestrator.py`

**Comment by PitButtchereit** [comment]
The functions of all modules need to be refactored, as there is duplicate code and unnecessary function calls. Most of the logic can be moved to the execute function of the respective module. We can discuss as a group if we want to move the logic for all modules into the respective execute function.

**Comment by FR-SON** [comment]
The Cohort tagger is not executed at the moment. It is called with `execute_and_save` but doesn't actually implement that function. It does nothing.

**Comment by PitButtchereit** [comment]
I have safe deleted the GenerationForm inside the `forms.py` of the Patient Journey Generator.
