### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by tkv29** [bptlab/TracEX#95]
This tasks including an exception handling for errors which could occuring while extracting.

- [x] if an error occurs it should be catched
- [x] the user should be informed that an error occurs 
- [x] all created artifacts should be cleared so there will be no side effects when starting a new extraction

**Comment by PitButtchereit** [comment]
![Image](https://github.com/bptlab/TracEX/assets/116184086/2b56aff4-3e5b-44b8-bf67-bc581a084d22)

Error in line 77 with duration

**Comment by PitButtchereit** [comment]
activity labeler line 62

**Comment by FR-SON** [comment]
![Image](https://github.com/bptlab/TracEX/assets/93994888/b956e379-4550-499c-8e2f-9ed6491af399)
There is a variable `valid_cohort_data`, but the validation seems off. It should be checked, if age is a numerical value.
