### ISSUE TITLE
Adapt Test Mode for presentation

### ISSUE THREAD

**Issue by tkv29** [bptlab/TracEX#97]
This task includes the adaptation of the TEST Mode to the db and progress bar:

- [x] When turning on the TEST Mode the test trace is being loaded from the db
- [x] progress bar is working in the test mode

**Comment by PitButtchereit** [comment]
If we want to show the Trace Comparator in the Demo I suggest the following: Generating the result from the Trace Comparator in advance to the presentation as this is the modules that currently takes the longest time to execute.

**Comment by soeren227** [comment]
I'm definetly open to that, but first we should discuss if we want to present this feature in the technical presentation.
@nils-schmitt suggested to keep it for the Endpresentation to ensure that we have enough content for that as well.
Thoughts?

**Comment by tkv29** [comment]
@soeren227 @PitButtchereit the trace comparator is not part of the demo
